In [1]:
import pandas as pd

In [2]:
airbnb=pd.read_csv("train.csv")

In [ ]:
airbnb.count()

In [3]:
airbnb=airbnb.drop(columns=['neighbourhood','description','id','name','thumbnail_url','zipcode',\
                            'latitude','longitude','city','first_review','last_review'])

In [19]:
airbnb.describe()

log_price     amenities  accommodates     bathrooms  \
count  74111.000000  74111.000000  74111.000000  74111.000000   
mean       4.782069     17.602407      3.155146      1.234628   
std        0.717394      6.936947      2.153589      0.581386   
min        0.000000      1.000000      1.000000      0.000000   
25%        4.317488     13.000000      2.000000      1.000000   
50%        4.709530     17.000000      2.000000      1.000000   
75%        5.220356     22.000000      4.000000      1.000000   
max        7.600402     86.000000     16.000000      8.000000   

       host_has_profile_pic  host_identity_verified    host_since  \
count          74111.000000            74111.000000  74111.000000   
mean               0.996951                0.673800      4.949022   
std                0.055138                0.468825      1.836001   
min                0.000000                0.000000      2.000000   
25%                1.000000                0.000000      4.000000   
50%                1.000000                1.000000      5.000000   
75%                1.000000                1.000000      6.000000   
max                1.000000                1.000000     11.000000   

       instant_bookable  number_of_reviews  review_scores_rating  \
count      74111.000000       74111.000000          74111.000000   
mean           0.262458          20.900568             94.067365   
std            0.439973          37.828641              6.896002   
min            0.000000           0.000000             20.000000   
25%            0.000000           1.000000             93.000000   
50%            0.000000           6.000000             94.067365   
75%            1.000000          23.000000             99.000000   
max            1.000000         605.000000            100.000000   

           bedrooms          beds  
count  74111.000000  74111.000000  
mean       1.265467      1.709611  
std        0.851671      1.253389  
min        0.000000      0.000000  
25%        1.000000      1.000000  
50%        1.000000      1.000000  
75%        1.000000      2.000000  
max       10.000000     18.000000

In [ ]:
airbnb.head(10)

In [ ]:
airbnb.amenities[26]

In [4]:
def count_amen(x):
    return x.count(',')+1

airbnb['amenities']=airbnb['amenities'].apply(count_amen)  #amenities는 하나하나 레이블링 하기에 데이터가 복잡해지므로 개수로 바꿈

In [29]:
import matplotlib.pyplot as plt

In [ ]:
airbnb.plot(y='log_price', kind='box')

In [ ]:
airbnb.hist(column='log_price',bins=20)

In [ ]:
airbnb.dtypes

In [13]:
airbnb

log_price property_type        room_type  amenities  accommodates  \
0       5.010635     Apartment  Entire home/apt          9             3   
1       5.129899     Apartment  Entire home/apt         15             7   
2       4.976734     Apartment  Entire home/apt         19             5   
3       6.620073         House  Entire home/apt         15             4   
4       4.744932     Apartment  Entire home/apt         12             2   
5       4.442651     Apartment     Private room         10             2   
6       4.418841     Apartment  Entire home/apt         21             3   
7       4.787492   Condominium  Entire home/apt         26             2   
8       4.787492         House     Private room         21             2   
9       3.583519         House     Private room         13             2   
10      4.605170     Apartment     Private room         15             2   
11      5.010635         House  Entire home/apt         22             4   
12      4.248495     Apartment     Private room         17             2   
13      5.298317     Apartment  Entire home/apt         25             6   
14      4.955827     Apartment  Entire home/apt          7             2   
15      4.094345     Apartment     Private room         12             2   
16      4.317488          Loft     Private room         18             2   
17      4.595120     Townhouse     Private room         19             2   
18      4.882802     Apartment  Entire home/apt         18             2   
19      4.595120         House  Entire home/apt         24             8   
20      4.382027         House     Private room         21             2   
21      3.688879         House     Private room         11             2   
22      4.905275     Apartment  Entire home/apt         29             4   
23      4.007333         House     Private room         16             2   
24      6.956545     Apartment  Entire home/apt         14             4   
25      5.003946     Apartment  Entire home/apt         44             6   
26      4.553877     Apartment  Entire home/apt         14             2   
27      5.003946     Apartment  Entire home/apt         21             4   
28      5.192957     Apartment  Entire home/apt         15             3   
29      4.653960     Apartment     Private room         18             3   
...          ...           ...              ...        ...           ...   
74081   6.907755         Other  Entire home/apt         18            16   
74082   4.174387         House     Private room         17             1   
74083   5.010635     Apartment     Private room         11             2   
74084   5.843544         Other  Entire home/apt         19             4   
74085   4.653960     Apartment  Entire home/apt         15             2   
74086   4.174387         House     Private room          9             2   
74087   4.477337     Apartment  Entire home/apt         22             4   
74088   4.905275         House  Entire home/apt         18             5   
74089   4.605170         House     Private room         23             2   
74090   4.317488         House     Private room         21             2   
74091   5.010635     Apartment  Entire home/apt          8             2   
74092   4.700480     Apartment  Entire home/apt         26             4   
74093   4.948760         House  Entire home/apt         18             4   
74094   3.688879     Apartment     Private room         15             2   
74095   4.382027     Apartment  Entire home/apt          9             2   
74096   3.912023     Apartment     Private room         16             2   
74097   4.700480     Apartment     Private room         16             2   
74098   4.553877     Apartment  Entire home/apt         20             4   
74099   4.276666   Condominium     Private room         17             2   
74100   4.605170     Apartment     Private room         23             2   
74101   4.584967     Apartment     Private room        

In [5]:
import numpy as np
import datetime
airbnb['host_since']=datetime.datetime.now().year-pd.DatetimeIndex(airbnb['host_since']).year

In [14]:
airbnb.count()

log_price                 74111
property_type             74111
room_type                 74111
amenities                 74111
accommodates              74111
bathrooms                 74111
bed_type                  74111
cancellation_policy       74111
cleaning_fee              74111
host_has_profile_pic      74111
host_identity_verified    74111
host_response_rate        55812
host_since                74111
instant_bookable          74111
number_of_reviews         74111
review_scores_rating      74111
bedrooms                  74111
beds                      74111
dtype: int64

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
imputer=SimpleImputer()

In [9]:
#impute missing values

airbnb[['review_scores_rating']]=imputer.fit_transform(airbnb[['review_scores_rating']])
imputer.set_params(strategy='median')
airbnb[['bathrooms']]=imputer.fit_transform(airbnb[['bathrooms']])
airbnb[['bedrooms']]=imputer.fit_transform(airbnb[['bedrooms']])
airbnb[['beds']]=imputer.fit_transform(airbnb[['beds']])
airbnb[['host_since']]=imputer.fit_transform(airbnb[['host_since']])

imputer.set_params(strategy='most_frequent')
airbnb[['host_has_profile_pic']]=imputer.fit_transform(airbnb[['host_has_profile_pic']])
airbnb[['host_identity_verified']]=imputer.fit_transform(airbnb[['host_identity_verified']])

In [ ]:
airbnb[['review_scores_rating']]

In [15]:
#airbnb.host_response_rate 거의 100프로이고 missing value 많으므로 제외
airbnb=airbnb.drop(columns=['host_response_rate'])

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
ord_enc=OrdinalEncoder()

In [42]:
ord_enc.fit(airbnb[['host_has_profile_pic','host_identity_verified','instant_bookable','cleaning_fee','cancellation_policy']])

OrdinalEncoder(categories='auto', dtype=<class 'numpy.float64'>)

In [43]:
ord_enc.categories_

[array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([False, True], dtype=object),
 array(['flexible', 'moderate', 'strict', 'super_strict_30',
        'super_strict_60'], dtype=object)]

In [17]:
airbnb[['host_has_profile_pic','host_identity_verified','instant_bookable']]=ord_enc.transform(airbnb[['host_has_profile_pic','host_identity_verified','instant_bookable']])

In [18]:
airbnb.head(5)

log_price property_type        room_type  amenities  accommodates  \
0   5.010635     Apartment  Entire home/apt          9             3   
1   5.129899     Apartment  Entire home/apt         15             7   
2   4.976734     Apartment  Entire home/apt         19             5   
3   6.620073         House  Entire home/apt         15             4   
4   4.744932     Apartment  Entire home/apt         12             2   

   bathrooms  bed_type cancellation_policy  cleaning_fee  \
0        1.0  Real Bed              strict          True   
1        1.0  Real Bed              strict          True   
2        1.0  Real Bed            moderate          True   
3        1.0  Real Bed            flexible          True   
4        1.0  Real Bed            moderate          True   

   host_has_profile_pic  host_identity_verified  host_since  instant_bookable  \
0                   1.0                     1.0         7.0               0.0   
1                   1.0                     0.0         2.0               1.0   
2                   1.0                     1.0         3.0               1.0   
3                   1.0                     1.0         4.0               0.0   
4                   1.0                     1.0         4.0               1.0   

   number_of_reviews  review_scores_rating  bedrooms  beds  
0                  2            100.000000       1.0   1.0  
1                  6             93.000000       3.0   3.0  
2                 10             92.000000       1.0   3.0  
3                  0             94.067365       2.0   2.0  
4                  4             40.000000       0.0   1.0

In [37]:
airbnb['property_type'].value_counts()

In [38]:
airbnb['room_type'].value_counts()

Real Bed         72028
Futon              753
Pull-out Sofa      585
Airbed             477
Couch              268
Name: bed_type, dtype: int64

In [39]:
airbnb['bed_type'].value_counts()

Real Bed         72028
Futon              753
Pull-out Sofa      585
Airbed             477
Couch              268
Name: bed_type, dtype: int64

In [ ]:
#property type은 너무 쓸데없이 많은 종류가 있고 apartment에 치우쳐 져있으므로 room_type만 사용하는게 낫다고 생각하여 삭제
#bed type은 real bed가 대부분의 데이터를 차지하므로 잘못 학습할 수 있으므로 삭제
airbnb=airbnb.drop(columns=['property_type','bed_type']